import type { Metadata } from 'next';
import '../globals.css';
import Header from '@/components/Header/Header';
import { Raleway } from 'next/font/google';
import { Manrope } from 'next/font/google';
import { Sansation } from '@/fonts/Sansation';
import { getLanguageFromParams } from '@/lib/language';
import Sprite from '@/components/Sprite/Sprite';

const raleway = Raleway({ subsets: ['latin'], variable: '--font-raleway' });
const manrope = Manrope({ subsets: ['latin'], variable: '--font-manrope' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = async ({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: string };
}) => {
  const resolvedParams = await params;
  const language = getLanguageFromParams(resolvedParams);
  return (
    <html lang={language}>
      <body
        className={`${raleway.variable} ${manrope.variable} ${Sansation.variable} antialiased`}
      >
        <Sprite />
        <Header language={language} />
        <main>{children}</main>
      </body>
    </html>
  );
};

export default RootLayout;
